-- LEVEL 1: BASIC BUSINESS METRICS
 
-- Q1: Which 10 customers have spent the most money?
SELECT 
    c.first_name, 
    c.last_name, 
    SUM(i.list_price * i.quantity) AS total_spent
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items i ON o.order_id = i.order_id
GROUP BY c.customer_id
ORDER BY total_spent DESC
LIMIT 10;

-- How many unique products do we offer under each brand?
SELECT 
    b.brand_name, 
    COUNT(p.product_id) AS unique_product_count
FROM brands b
JOIN products p ON b.brand_id = p.brand_id
GROUP BY b.brand_name
ORDER BY unique_product_count DESC;

-- What is the total revenue generated by each store location?
SELECT 
    s.store_name, 
    SUM(i.list_price * i.quantity * (1 - i.discount)) AS total_revenue
FROM stores s
JOIN orders o ON s.store_id = o.store_id
JOIN order_items i ON o.order_id = i.order_id
GROUP BY s.store_name
ORDER BY total_revenue DESC;

-- Which product categories (e.g., Mountain Bikes, Road Bikes) have the highest average unit price?
SELECT 
    c.category_name, 
    ROUND(AVG(p.list_price)) AS average_unit_price
FROM categories c
JOIN products p ON c.category_id = p.category_id
GROUP BY c.category_name
ORDER BY average_unit_price DESC;

-- List all orders that are still "Pending" or "Processing" to identify potential fulfillment bottlenecks.

SELECT 
    o.order_id, 
    o.order_status, 
    o.order_date, 
    s.store_name
FROM orders o
JOIN stores s ON s.store_name = s.store_name
WHERE o.order_status IN (1, 2)
ORDER BY o.order_date ASC;

-- Identify the top 5 most expensive bikes we currently have in stock
select distinct p.product_name, p.product_id, p.list_price from products p
join stocks s on p.product_id = s.product_id
where s.quantity > 0
group by p.product_name
order by p.list_price DESC
limit 5;











